name: Build

on:
  push:
    paths:
      - "bookmarker-api/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "bookmarker-api/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify